name: Quantization Lab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run quantization demo (non-interactive)
        run: |
          python quantization_demo.py --Ts 0.5 0.1 --L 4 --xmin 0 --xmax 4 --period 2 --outdir outputs --no-show

      - name: Upload outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: quantization-outputs
          path: outputs/
